### ISSUE TITLE
Type 2 error on all test samples

### ISSUE THREAD

**Issue by jkennedyvz** [ManhNho/Faceless#1]
Hi, I tried to use this project on a quick selection of recent fakes - the results did not inspire confidence.

Additionally https://github.com/ManhNho/Faceless/blob/main/faceless.py#L57 appears to be a redundant resize operation. 

Complete failure:
https://www.youtube.com/watch?v=LgP49SyGF1w
https://www.youtube.com/watch?v=UiU7HkHtYE0
https://www.youtube.com/watch?v=8l0nqZn0c9E
https://www.youtube.com/watch?v=LFcs-sPhkME
https://www.youtube.com/watch?v=AmAaLbJVGnI

Results are not useful:
https://www.youtube.com/watch?v=PKQJPpceWVM

**Comment by ManhNho** [comment]
Hi, the failed results depend on the face manipulation methods or synthesis algorithm and post-production video editing.
My training dataset is Celeb-DF, so
I also have plan for new version `faceless`, stay tune for the new one.
